/*
 * OpenAPI proxy service
 *
 * This is the OpenAPI definition of the proxy service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package services

import (
	"chaingate/proxy-service/proxyApi"
	"context"
	"errors"
	"net/http"
)

// ExchangeRateApiService is a service that implements the logic for the ExchangeRateApiServicer
// This service should implement the business logic for every endpoint for the ExchangeRateApi API.
// Include any external packages or services that will be required by this service.
type ExchangeRateApiService struct {
}

// NewExchangeRateApiService creates a default api service
func NewExchangeRateApiService() proxyApi.ExchangeRateApiServicer {
	return &ExchangeRateApiService{}
}

// GetExchangeRate - get exchange rate
func (s *ExchangeRateApiService) GetExchangeRate(ctx context.Context, fiat string, crypto string) (proxyApi.ImplResponse, error) {
	// TODO - update GetExchangeRate with the required logic for this service method.
	// Add api_exchange_rate_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ExchangeRate{}) or use other options such as http.Ok ...
	//return Response(200, ExchangeRate{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return proxyApi.Response(http.StatusNotImplemented, nil), errors.New("GetExchangeRate method not implemented")
}
