/*
 * OpenAPI proxy service
 *
 * This is the OpenAPI definition of the proxy service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package services

import (
	"chaingate/proxy-service/proxyApi"
	"context"
	"errors"
	"net/http"
)

// WebhookApiService is a service that implements the logic for the WebhookApiServicer
// This service should implement the business logic for every endpoint for the WebhookApi API.
// Include any external packages or services that will be required by this service.
type WebhookApiService struct {
}

// NewWebhookApiService creates a default api service
func NewWebhookApiService() proxyApi.WebhookApiServicer {
	return &WebhookApiService{}
}

// SendWebhook - send webhook
func (s *WebhookApiService) SendWebhook(ctx context.Context, webHook proxyApi.WebHook) (proxyApi.ImplResponse, error) {
	// TODO - update SendWebhook with the required logic for this service method.
	// Add api_webhook_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return proxyApi.Response(http.StatusNotImplemented, nil), errors.New("SendWebhook method not implemented")
}
