openapi: 3.0.0
servers:
  - url: 'http://localhost:8001/api'
info:
  description: >-
    This is the OpenAPI definition of the proxy service.
  version: 1.0.0
  title: OpenAPI proxy service
tags:
  - name: email
  - name: webhook
  - name: conversion
paths:
  /email:
    post:
      tags:
        - email
      summary: send email
      operationId: sendEmail
      responses:
        '200':
          description: successful operation
        '400':
          description: bad request
      requestBody:
        $ref: '#/components/requestBodies/EmailRequestDto'
        
  /price-conversion:
    get:
      tags: 
        - conversion
      summary: get price conversion
      operationId: getPriceConversion
      parameters:
        - in: query
          name: amount
          required: true
          schema:
            type: string
        - in: query
          name: src_currency
          required: true
          schema:
            type: string
        - in: query
          name: dst_currency
          schema:
            type: string
          required: true
        - in: query
          name: mode
          schema:
            type: string
            enum:
              - main
              - test
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceConversionResponseDto'
        '400':
          description: bad request
        
  /webhook:
    post:
      tags: 
        - webhook
      summary: send webhook
      operationId: sendWebhook
      responses:
        '200':
          description: successful operation
        '400':
          description: bad request
      requestBody:
        $ref: '#/components/requestBodies/WebHookRequestDto'
        
components:
  requestBodies:
    EmailRequestDto:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EmailRequestDto'
    WebHookRequestDto:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WebHookRequestDto'
  schemas:
    EmailRequestDto:
      title: Email Request DTO
      type: object
      required:
        - name
        - email_to
        - subject
        - content
      properties:
        name:
          type: string
        email_to:
          type: string
        subject:
          type: string
        content:
          type: string
    PriceConversionResponseDto:
      title: Price Conversion Response DTO
      type: object
      properties:
        src_currency:
          type: string
        dst_currency:
          type: string
        price:
          type: string
    WebHookRequestDto:
      title: WebHook Request Dto
      type: object
      required:
        - url
        - body
      properties:
        url:
          type: string
        body:
          $ref: '#/components/schemas/WebHookBody'
    WebHookBody:
      title: WebHook Body
      type: object
      required:
        - data
        - signature
      properties:
        data:
          $ref: '#/components/schemas/WebHookData'
        signature:
          type: string
    WebHookData:
      title: WebHook Data
      type: object
      required:
        - payment_id
        - pay_address
        - price_amount
        - price_currency
        - pay_amount
        - pay_currency
        - actually_paid
        - payment_status
        - created_at
        - updated_at
      properties:
        payment_id:
          type: string
          format: uuid
        pay_address:
          type: string
        price_amount:
          type: number
          format: double
        price_currency:
          type: string
          enum:
            - usd
            - chf
        pay_amount:
          type: string
        pay_currency:
          type: string
          enum:
            - eth
            - btc
        actually_paid:
          type: string
        payment_status:
          type: string
          enum:
            - waiting
            - partially_paid
            - paid
            - sending
            - finished
            - expired
            - failed
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time